package com.github.klee0kai.crossbox.processor.poet

import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec


fun FileSpec.Builder.genLibComment() {
    addFileComment("Generated by Crossbox Library\n")
    addFileComment("Project https://github.com/klee0kai/crossbox\n")
    addFileComment("Copyright (c) 2025 Andrey Kuzubov")
}

fun PropertySpec.Builder.initFromConstructor(): PropertySpec.Builder = apply { initializer(build().name) }

